name: focus_assist
description: Phần mềm quản lý thời gian biểu và hỗ trợ tập trung - Focus Assist

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  path_provider: ^2.0.2
  table_calendar: ^3.0.0
  flutter_local_notifications: ^5.0.0
  rxdart:
  flutter_native_timezone:
  flutter_config: ^1.0.5
  image_picker:
  pie_chart: ^5.0.0
  flutter_calendar_carousel: ^2.0.1
  numberpicker: ^1.0.0
  audioplayers: ^0.18.0
  timezone: ^0.7.0
  firebase_auth: ^1.4.1
  google_sign_in: ^5.0.4
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.1.3
  photo_view: 0.11.1
  flutter_swiper: ^1.1.6
  crypto: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  percent_indicator: "^2.1.7+2"
  fluttertoast: ^8.0.6
  rflutter_alert: ^2.0.2
  curved_navigation_bar: ^0.3.7
  simple_animations: ^1.3.3
  simple_timer: ^2.0.0
  flutter_volume_slider: ^1.0.6
  flutter_gifimage: ^1.0.1
  provider: ^4.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/Database/
    - assets/default.png
    - assets/login/ui/UI_login_screen.png
    - assets/login/ui/UI_welcome_screen.png
    - assets/login/icon/facebook.png
    - assets/login/icon/google.png
    - assets/login/icon/twitter.png
    - assets/achievenment/Eggs/eggCarpentry.png
    - assets/achievenment/Eggs/eggElectric.png
    - assets/achievenment/Eggs/eggFire.png
    - assets/achievenment/Eggs/eggIce.png
    - assets/achievenment/Eggs/eggMagic.png
    - assets/achievenment/Eggs/eggRock.png
    - assets/achievenment/Eggs/eggSky.png
    - assets/achievenment/Eggs/eggWater.png
    - assets/achievenment/achieImage/
    - assets/achievenment/achieImage/TT02.png
    - assets/achievenment/achieImage/TT09.png
    - assets/achievenment/achieImage/TT10.png
    - assets/achievenment/achieImage/TT12.png
    - assets/achievenment/achieImage/
    - assets/achievenment/achieImage/TT15.png
    - assets/achievenment/achieImage/TT17.png
    - assets/achievenment/achieImage/TT20.png
    - assets/3.PNG
    - assets/Database/create_tables_script.sql
    - assets/achievenment/Eggs/eggBlue.png
    - assets/achievenment/Eggs/eggCheese.png
    - assets/achievenment/Eggs/eggChocolate.png
    - assets/achievenment/Eggs/eggCream.png
    - assets/achievenment/Eggs/eggDeepBlue.png
    - assets/achievenment/Eggs/eggDemon.png
    - assets/achievenment/Eggs/eggDiamod.png
    - assets/achievenment/Eggs/eggForest.png
    - assets/achievenment/Eggs/eggLoli.png
    - assets/achievenment/Eggs/eggSilver.png
    - assets/achievenment/Eggs/eggStrawberry.png
    - assets/achievenment/Eggs/eggSweety.png
    - assets/achievenment/move/
    - assets/achievenment/ui/
    - assets/achievenment/ui/background.png
    - assets/achievenment/ui/background_darkmode.jpg
    - assets/achievenment/ui/background_farm1.jpg
    - assets/achievenment/ui/ui_collection.png


    - assets/achievenment/ui/UI_shop_volumn.png
    - assets/Database/create_tables_script.sql
    - assets/images/focusTime_background.png
    - assets/images/clock.gif
    - assets/images/clock_darkmode.gif
    - assets/audio/Song1.mp3
    - assets/audio/Song2.mp3
    - assets/audio/coffeShop.mp3
    - assets/audio/guitar.mp3
    - assets/audio/piano.mp3
    - assets/audio/
    - assets/

    - assets/google_logo.png
    - assets/img_not_available.jpeg
    - assets/stickers/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
