--
-- File generated with SQLiteStudio v3.3.2 on Mon May 17 17:07:08 2021
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: LICHSUTIMER
CREATE TABLE LICHSUTIMER (
    MANGUOIDUNG TEXT,
    THOIGIAN DATETIME,
    KHOANGTHOIGIAN TIME,
    DAHOANTHANH BOOL,
    PRIMARY KEY (MANGUOIDUNG, THOIGIAN)
);

-- Table: MUCTIEU
CREATE TABLE MUCTIEU (
    MAMUCTIEU TEXT PRIMARY KEY,
    MANGUOIDUNG TEXT,
    MANHOM TEXT,
    TENMUCTIEU TEXT,
    MOTA TEXT,
    NGAYBATDAU DATE,
    LOAIHINH TEXT,
    CACNGAY INTEGER,
    SOLAN INTEGER,
    KHOANGTHOIGIAN TEXT
);

-- Table: NGUOIDUNG
CREATE TABLE NGUOIDUNG (
    MANGUOIDUNG TEXT PRIMARY KEY,
    TENTAIKHOAN TEXT,
    MATKHAU TEXT
);

-- Table: NHOMMUCTIEU
CREATE TABLE NHOMMUCTIEU (
    MANHOM TEXT PRIMARY KEY,
    MANGUOIDUNG TEXT,
    MAMUCTIEU TEXT,
    TENNHOM TEXT
);

-- Table: THANHTUU
CREATE TABLE THANHTUU (
    MATHANHTUU TEXT PRIMARY KEY,
    TENTHANHTUU TEXT,
    CAPDO INTEGER,
    VANG INTEGER
);

-- Table: THANHTUUNGUOIDUNG
CREATE TABLE THANHTUUNGUOIDUNG (
    MATHANHTUU TEXT,
    MANGUOIDUNG TEXT,
    PRIMARY KEY (MATHANHTUU, MANGUOIDUNG)
);

-- Table: THONGKE
CREATE TABLE THONGKE (
    MAMUCTIEU TEXT,
    NGAYHOANTHANH DATE,
    PRIMARY KEY (MAMUCTIEU, NGAYHOANTHANH)
);

-- Table: THONGTINNGUOIDUNG
CREATE TABLE THONGTINNGUOIDUNG (
    MANGUOIDUNG TEXT PRIMARY KEY,
    HOTEN TEXT,
    ANH BLOB,
    VANG INTEGER,
    THONGBAO BOOL,
    THONGBAOSANG BOOL,
    THONGBAOTOI BOOL,
    THOIGIANTHONGBAOSANG TIME,
    THOIGIANTHONGBAOTOI TIME,
    DARKMODE BOOL,
    PRIVACYLOCK BOOL,
    LOCKPASSCODE TEXT
);

-- Table: TRICHDAN
CREATE TABLE TRICHDAN (
    MATRICHDAN TEXT PRIMARY KEY,
    TRICHDAN TEXT,
    TACGIA TEXT
);

-- Table: VATPHAM
CREATE TABLE VATPHAM (
    MAVATPHAM TEXT PRIMARY KEY,
    TENVATPHAM TEXT,
    MOTA TEXT,
    GIA INTEGER,
    DOHIEM INTEGER
);



-- Table: VATPHAMNGUOIDUNG
CREATE TABLE VATPHAMNGUOIDUNG (
    MAVATPHAM TEXT,
    MANGUOIDUNG TEXT,
    PRIMARY KEY (MAVATPHAM, MANGUOIDUNG)
);


INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP01', 'Thien', '?-?', 2000, 1);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP02', 'Quang', 'Nhom truong dep trai', 3000, 2);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP03', 'Phi', 'Best code', 500, 3);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP04', 'Nhu',  'Co ny ma giau ae', 1700, 4);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP05', 'Thanh', 'Best game', 2300, 4);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
