--
-- File generated with SQLiteStudio v3.3.2 on Mon May 17 17:07:08 2021
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: LICHSUTIMER
CREATE TABLE LICHSUTIMER (
    MANGUOIDUNG TEXT,
    THOIGIAN DATETIME,
    KHOANGTHOIGIAN TIME,
    DAHOANTHANH BOOL,
    PRIMARY KEY (MANGUOIDUNG, THOIGIAN)
);

-- Table: MUCTIEU
CREATE TABLE MUCTIEU (
    MAMUCTIEU TEXT PRIMARY KEY,
    MANGUOIDUNG TEXT,
    MANHOM TEXT,
    TENMUCTIEU TEXT,
    MOTA TEXT,
    NGAYBATDAU INTEGER,
    LOAIHINH TEXT,
    CACNGAY INTEGER,
    SOLAN INTEGER,
    KHOANGTHOIGIAN INTEGER
);

-- Table: NGUOIDUNG
CREATE TABLE NGUOIDUNG (
    MANGUOIDUNG TEXT PRIMARY KEY,
    TENTAIKHOAN TEXT,
    MATKHAU TEXT
);

-- Table: NHOMMUCTIEU
CREATE TABLE NHOMMUCTIEU (
    MANHOM TEXT PRIMARY KEY,
    MANGUOIDUNG TEXT,
    MAMUCTIEU TEXT,
    TENNHOM TEXT
);

-- Table: THANHTUU
CREATE TABLE THANHTUU (
    MATHANHTUU TEXT PRIMARY KEY,
    TENTHANHTUU TEXT,
    MOTA TEXT,
    CAPDO INTEGER,
    VANG INTEGER
);

-- Table: THANHTUUNGUOIDUNG
CREATE TABLE THANHTUUNGUOIDUNG (
    MATHANHTUU TEXT,
    MANGUOIDUNG TEXT,
    PRIMARY KEY (MATHANHTUU, MANGUOIDUNG)
);

-- Table: THONGKE
CREATE TABLE THONGKE (
    MAMUCTIEU TEXT,
    NGAYHOANTHANH INTEGER,
    PRIMARY KEY (MAMUCTIEU, NGAYHOANTHANH)
);

-- Table: THONGTINNGUOIDUNG
CREATE TABLE THONGTINNGUOIDUNG (
    MANGUOIDUNG TEXT PRIMARY KEY,
    HOTEN TEXT,
    ANH BLOB,
    VANG INTEGER,
    THONGBAO BOOL,
    THONGBAOSANG BOOL,
    THONGBAOTOI BOOL,
    THOIGIANTHONGBAOSANG TIME,
    THOIGIANTHONGBAOTOI TIME,
    DARKMODE BOOL,
    PRIVACYLOCK BOOL,
    LOCKPASSCODE TEXT
);

-- Table: TRICHDAN
CREATE TABLE TRICHDAN (
    MATRICHDAN TEXT PRIMARY KEY,
    TRICHDAN TEXT,
    TACGIA TEXT
);

-- Table: VATPHAM
CREATE TABLE VATPHAM (
    MAVATPHAM TEXT PRIMARY KEY,
    TENVATPHAM TEXT,
    MOTA TEXT,
    GIA INTEGER,
    DOHIEM INTEGER
);

-- Table: POKEMON
CREATE TABLE POKEMON (
    NAMEPOKEMON TEXT,
    MANGUOIDUNG TEXT,
    LEVELPOKEMON INTEGER,
    DOHIEM INTEGER
);


-- Table: VATPHAMNGUOIDUNG
CREATE TABLE VATPHAMNGUOIDUNG (
    MAVATPHAM TEXT,
    MANGUOIDUNG TEXT,
    PRIMARY KEY (MAVATPHAM, MANGUOIDUNG)
);

-- Table: THAMSO
CREATE TABLE THAMSO (
    DADANGNHAP BOOL,
    MANGUOIDUNG TEXT,
    PRIMARY KEY (DADANGNHAP, MANGUOIDUNG)
);

INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP01', 'Carpentry', '?', 450, 1);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP02', 'Electric', '?', 2200, 2);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP03', 'Fire', '?', 6500, 3);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP04', 'Ice',  '?', 10000, 4);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP05', 'Magic', '?', 600, 1);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP06', 'Rock', '?', 2000, 2);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP07', 'Sky', '?', 5500, 3);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP08', 'Water', '?', 11000, 4);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP09', 'Blue', '?', 330, 1);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP10', 'Cheese', '?', 3200, 2);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP11', 'Chocolate', '?', 6600, 3);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP12', 'Cream', '?', 10500, 4);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP13', 'DeepBlue',  '?', 200, 1);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP14', 'Demon', '?', 2900, 2);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP15', 'Diamod', '?', 4900, 3);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP16', 'Forest', '?', 15000, 4);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP17', 'Loli', '?', 160, 1);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP18', 'Silver',  '?', 3170, 2);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP19', 'Strawberry', '?', 4500, 3);
INSERT INTO VATPHAM (MAVATPHAM,TENVATPHAM,MOTA,GIA,DOHIEM) VALUES ('VP20', 'Sweety',  '?', 12500, 4);


INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT01', 'Blue', 'Trứng Blue', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT02', 'Carpentry', 'Trứng Carpentry', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT03', 'Cheese', 'Trứng Cheese', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT04', 'Chocolate', 'Trứng Chocolate', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT05', 'Cream', 'Trứng Cream', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT06', 'DeepBlue', 'Trứng DeepBlue', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT07', 'Demon', 'Trứng Demon', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT08', 'Diamod', 'Trứng Diamod', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT09', 'Electric', 'Trứng Electric', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT10', 'Fire', 'Trứng Fire', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT11', 'Forest', 'Trứng Forest', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT12', 'Ice', 'Trứng Ice', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT13', 'Loli', 'Trứng Loli', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT14', 'Magic', 'Trứng Magic', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT15', 'Rock', 'Trứng Rock', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT16', 'Silver', 'Trứng Silver', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT17', 'Sky', 'Trứng Sky',1,200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT18', 'Strawberry', 'Trứng Strawberry', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT19', 'Sweety', 'Trứng Sweety', 1, 200);
INSERT INTO THANHTUU (MATHANHTUU,TENTHANHTUU,MOTA,CAPDO,VANG) VALUES ('TT20', 'Water', 'Trứng Water', 1, 200);


INSERT INTO THAMSO (0, '');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
